### ISSUE TITLE
keycodes.h:42:20: error: '_GAME1' undeclared here (not in a function); did you mean '_HOME'?

### ISSUE THREAD

**Issue by tms-gvd** [ChuseCubr/mini-ryoku#2]
Hi, thanks for the layout, can't wait to try it!
I am running into an error when compiling with `qmk compile -kb ferris/sweep -km mini-ryoku`, find attached the log.
[error.txt](https://github.com/ChuseCubr/mini-ryoku/files/15029098/error.txt)

**Comment by ChuseCubr** [comment]
Oops, messed up porting my personal setup here. Sit tight, I'll be pushing a commit in a bit.

**Comment by ChuseCubr** [comment]
Hopefully fixed in 7a710dde8718acfabfd5125f6926116f3b5d229d.
Unfortunately, all I can do at the moment is confirm that it builds, and not that it works. Feel free to try it, and do tell me if it works; I'll keep this open in case it doesn't.
I'll be logging off soon, so I'll have to get back to you tomorrow.

**Comment by tms-gvd** [comment]
I'll try tomorrow, thanks a lot!

**Comment by tms-gvd** [comment]
I flash a modified version from your last commit and it works well, thanks!
